FROM php:8.2-cli

RUN apt-get update && apt-get install -y libzip-dev libpq-dev zlib1g-dev zip git

RUN docker-php-ext-install pdo pdo_mysql mysqli zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --quiet

RUN  curl -sS https://get.symfony.com/cli/installer | bash \
    &&   mv /root/.symfony5/bin/symfony /usr/local/bin/symfony

RUN groupadd -g 1000 appuser && useradd -r -u 1000 -g appuser appuser

RUN mkdir -p /home/appuser/.composer/cache/repo/https---asset-packagist.org \
    && mkdir /home/appuser/.composer/cache/files

RUN chown -R appuser:appuser /home/appuser && chmod -R 775 /home/appuser

USER appuser

ENV COMPOSER_NO_INTERACTION=1

WORKDIR /var/www/project